//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkOracle
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OracleEntitiesMaison : DbContext
    {
        public OracleEntitiesMaison()
            : base("name=OracleEntitiesMaison")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COUR> COURS { get; set; }
        public virtual DbSet<EMPLOYE> EMPLOYEs { get; set; }
        public virtual DbSet<INSCRIT> INSCRITs { get; set; }
        public virtual DbSet<PARTICIPER> PARTICIPERs { get; set; }
        public virtual DbSet<PROJET> PROJETs { get; set; }
        public virtual DbSet<SEMINAIRE> SEMINAIREs { get; set; }
    
        public virtual int INS_COURS(string pCODECOURS, string pLIBELLECOURS, Nullable<decimal> pNBJOURS)
        {
            var pCODECOURSParameter = pCODECOURS != null ?
                new ObjectParameter("PCODECOURS", pCODECOURS) :
                new ObjectParameter("PCODECOURS", typeof(string));
    
            var pLIBELLECOURSParameter = pLIBELLECOURS != null ?
                new ObjectParameter("PLIBELLECOURS", pLIBELLECOURS) :
                new ObjectParameter("PLIBELLECOURS", typeof(string));
    
            var pNBJOURSParameter = pNBJOURS.HasValue ?
                new ObjectParameter("PNBJOURS", pNBJOURS) :
                new ObjectParameter("PNBJOURS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_COURS", pCODECOURSParameter, pLIBELLECOURSParameter, pNBJOURSParameter);
        }
    
        public virtual int INS_EMPLOYE(Nullable<decimal> pNUMEMP, string pNOMEMP, string pPRENOMEMP, string pPOSTE, Nullable<decimal> pSALAIRE, Nullable<decimal> pPRIME, string pCODEPROJET, Nullable<decimal> pSUP)
        {
            var pNUMEMPParameter = pNUMEMP.HasValue ?
                new ObjectParameter("PNUMEMP", pNUMEMP) :
                new ObjectParameter("PNUMEMP", typeof(decimal));
    
            var pNOMEMPParameter = pNOMEMP != null ?
                new ObjectParameter("PNOMEMP", pNOMEMP) :
                new ObjectParameter("PNOMEMP", typeof(string));
    
            var pPRENOMEMPParameter = pPRENOMEMP != null ?
                new ObjectParameter("PPRENOMEMP", pPRENOMEMP) :
                new ObjectParameter("PPRENOMEMP", typeof(string));
    
            var pPOSTEParameter = pPOSTE != null ?
                new ObjectParameter("PPOSTE", pPOSTE) :
                new ObjectParameter("PPOSTE", typeof(string));
    
            var pSALAIREParameter = pSALAIRE.HasValue ?
                new ObjectParameter("PSALAIRE", pSALAIRE) :
                new ObjectParameter("PSALAIRE", typeof(decimal));
    
            var pPRIMEParameter = pPRIME.HasValue ?
                new ObjectParameter("PPRIME", pPRIME) :
                new ObjectParameter("PPRIME", typeof(decimal));
    
            var pCODEPROJETParameter = pCODEPROJET != null ?
                new ObjectParameter("PCODEPROJET", pCODEPROJET) :
                new ObjectParameter("PCODEPROJET", typeof(string));
    
            var pSUPParameter = pSUP.HasValue ?
                new ObjectParameter("PSUP", pSUP) :
                new ObjectParameter("PSUP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_EMPLOYE", pNUMEMPParameter, pNOMEMPParameter, pPRENOMEMPParameter, pPOSTEParameter, pSALAIREParameter, pPRIMEParameter, pCODEPROJETParameter, pSUPParameter);
        }
    
        public virtual int INS_INSCRIT(Nullable<decimal> pNUMEMP, string pCODESEMI, Nullable<System.DateTime> pDATEINSCRIT)
        {
            var pNUMEMPParameter = pNUMEMP.HasValue ?
                new ObjectParameter("PNUMEMP", pNUMEMP) :
                new ObjectParameter("PNUMEMP", typeof(decimal));
    
            var pCODESEMIParameter = pCODESEMI != null ?
                new ObjectParameter("PCODESEMI", pCODESEMI) :
                new ObjectParameter("PCODESEMI", typeof(string));
    
            var pDATEINSCRITParameter = pDATEINSCRIT.HasValue ?
                new ObjectParameter("PDATEINSCRIT", pDATEINSCRIT) :
                new ObjectParameter("PDATEINSCRIT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_INSCRIT", pNUMEMPParameter, pCODESEMIParameter, pDATEINSCRITParameter);
        }
    
        public virtual int MAJEMPLOYE(Nullable<decimal> pNUMEMP, Nullable<decimal> pAUGMENTATION, string pCOLONNE)
        {
            var pNUMEMPParameter = pNUMEMP.HasValue ?
                new ObjectParameter("PNUMEMP", pNUMEMP) :
                new ObjectParameter("PNUMEMP", typeof(decimal));
    
            var pAUGMENTATIONParameter = pAUGMENTATION.HasValue ?
                new ObjectParameter("PAUGMENTATION", pAUGMENTATION) :
                new ObjectParameter("PAUGMENTATION", typeof(decimal));
    
            var pCOLONNEParameter = pCOLONNE != null ?
                new ObjectParameter("PCOLONNE", pCOLONNE) :
                new ObjectParameter("PCOLONNE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MAJEMPLOYE", pNUMEMPParameter, pAUGMENTATIONParameter, pCOLONNEParameter);
        }
    }
}
